const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
export {
  SET_PRODUCT_DATA,
  ADD_TO_CART,
  CHANGE_PRODUCT_QUANTITY,
  INCREMENT,
  DECREMENT,
  REMOVE_PRODUCT_FROM_CART,
};
